apiVersion: v1
kind: Service
metadata:
  name: odrl-api
  namespace: odrl
  labels:
    app.kubernetes.io/name: odrl-api
    app.kubernetes.io/part-of: odrl-translator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: odrl-api
  ports:
    - name: http
      port: 8000
      targetPort: http