apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odrl
resources:
  - 00-namespace.yaml
  - 10-configmap.yaml
  - 30-postgres.yaml
  - 40-api-deployment.yaml
  - 41-api-service.yaml
  - 50-ui-deployment.yaml
  - 51-ui-service.yaml
  - 60-hpa.yaml
  - 70-ingress.yaml

images:
  - name: ghcr.io/OWNER/tfm-traductor-bidireccional-odrl-api
    newName: odrl-translator-api
    newTag: local

  - name: ghcr.io/OWNER/tfm-traductor-bidireccional-odrl-ui
    newName: odrl-translator-ui
    newTag: local
